export enum ActionTypes {
  LOGIN = 'LOGIN',
  LOGIN_FROM_COOKIES = 'LOGIN_FROM_COOKIES',
  ADD_EXPENCE = 'ADD_EXPENCE',
  EDIT_EXPENCE = 'EDIT_EXPENSE',
  DELETE_EXPENSE = 'DELETE_EXPENSE',
  RETRIEVE_MONTH = 'RETRIEVE_MONTH',
}
